This is push onlu
It was checke by me that my node server was running with nohup command
now when i enter inbound in EC2 instance an then on refresh still i was getting error or i was getting nothing
even I checked it in thunder client. now when  i just wanted to close the server with its PID but I did not get any process running of my server. because my  output.log file was not changing after refreshing may be I was even unable to put any  request but I saw that server is ging some error like when we let me past that logs of output.log "node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1898:16)
    at listenInCluster (node:net:1946:12)
    at Server.listen (node:net:2044:7)
    at Function.listen (/home/ubuntu/Assingment/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/home/ubuntu/Assingment/server.js:134:5)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1925:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3001
}"